### ISSUE TITLE
Datepicker for map of observations

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#47]
E.g. to view a map of air temperature from 3 days ago.

Need to decide which component this datepicker belongs too. It will only apply to observations (not platforms), so maybe we need a *observations-map.component.html* file.

Maybe just have a single date picker (i.e. just selecting a endDate, not a endDate AND startDate). Then show anything from the hour leading up to this endDate?

**Comment by Gramcito** [comment]
Commit [7236ae5](https://github.com/birminghamurbanobservatory/public-data-hub/commit/7236ae512e05695de164963ae74ef04161c4dbc3) adds the date picker which is shown only when the user viewing the observed property map; though might be better to be there all the time but disabled when on the platform view.

By default only the most recent hours worth of observations are show, as before, but when the user selects a date (and possibly a time) any observations in the preceding hour are shown; the date-time is maintained even when the user changes the observed property rather than it being reset each time. 

Have a play.

**Comment by SiBell** [comment]
Having had a quick play this is excellent. Big fan of the phrase "time travel". I actually quite like how it appears when an observed property is selected, so I would worry about having is present (and disabled) when looking at Sensor Platforms.

**Comment by SiBell** [comment]
One slight bug, and I'm being really picky (no pun intended) here: although the date-time in the datepicker is maintained when switching between variables, it is not maintained during a page refresh. It is for the first variable, but if you then switch to a different variable then the timeframe is lost.

@Gramcito Is it possible to initialise the datepicker on page load if a time has been set in the query parameters?

**Comment by SiBell** [comment]
Sorry, another picky comment: when a date-time is selected, is there an option for the date-time to be written in British rather than American format, i.e. d/m/y rather than m/d/y?

**Comment by Gramcito** [comment]
Updated to address both issues above.
