### ISSUE TITLE
Can't scroll plot page when datepicker is open

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#86]
This occurs on both mobile and desktop, but is most annoying on mobile because unless you click on the datepicker when it's at the very top of the page you then can't see the `Set` button at the bottom.

This might be out of our control, i.e. something the datepicker is controlling, although there might be a workaround? E.g. when datepicker button is clicked we automatically scroll the page so that the datepicker is at the top.

**Comment by SiBell** [comment]
This is an annoying one to replicate. Here's an example of the issue on my Galaxy S9:

<img width="382" alt="Screenshot 2020-07-02 at 11 18 21" src="https://user-images.githubusercontent.com/7696671/86347157-cd403280-bc55-11ea-9de3-10563be6f55d.png">

But when I try it in Google Chrome when simulating a Galaxy S5 it tends to work ok, ensuring that the datepicker fills the page.

<img width="373" alt="Screenshot 2020-07-02 at 11 16 21" src="https://user-images.githubusercontent.com/7696671/86346942-881c0080-bc55-11ea-891b-0ef4cfa57149.png">

If there's not an easy fix, then we might be able to get away with ignoring this issue.

**Comment by Gramcito** [comment]
Yes, out of our control. Ironically some just posted the same issue on the repo. I played around with this on the iPhone and can replicate and as a user work around it. 

I suspect a marginal issue, as I do not see that many mobile users for your site, simply because of the map and graphs... not easy to view on mobile. Would be nice for it to work... so to that end:

...something that might work is that I have changed the datepicker repo as it seems the original project has been abandoned but there is a fork being maintained. Pull the latest and do an npm install.

**Comment by SiBell** [comment]
Will do

**Comment by SiBell** [comment]
Definitely worth using this maintained version. For starters it uses a hyphen rather than a tilde to separate a date range.

It doesn't completely solve the issue, but as you say, you can just about work around it on mobile.

Closing issue.
