### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by SiBell** [birminghamurbanobservatory/public-data-hub#91]
So it's consistent with the [rest](https://birminghamurbanobservatory.com/about/) of the website.

Double check it's actually pushed to the bottom of the page, even when there's little content above it.

**Comment by SiBell** [comment]
Hi @Gramcito, do you think you have a quick crack at adding a footer (to appear on all pages). I had a quick go at adding one, but it went horribly wrong and ended up appearing behind the Deployment Legend.

Don't worry about the content, just give it a background colour and leave it blank for now. I can add all the same content that appears on the other applications, e.g. [here](https://birminghamurbanobservatory.com/).

I've managed to get all the headers pretty consistent between the 3 applications now, so the user shouldn't really notice when they transition between them ([landing page](https://birminghamurbanobservatory.com/), [live obs](https://live.birminghamurbanobservatory.com), [data hub](https://data.birminghamurbanobservatory.com/)). This was a right faff!

**Comment by SiBell** [comment]
Note to self: Add some text in the footer that says "This part of the website is still in beta. You may find a few bugs."

**Comment by Gramcito** [comment]
Yes, that could be tricky but will have a look this morning.

**Comment by Gramcito** [comment]
Okay, so I see why you had a problem. Actually I don't see at all. Why the Deployments div's position in the page is being totally ignored I have no idea....

**Comment by Gramcito** [comment]
Almost there....

**Comment by SiBell** [comment]
Sounds like this has been a "fun" one....

**Comment by Gramcito** [comment]
Ha ha! You have no idea... 

I started work today just before 0700, with exception of lunch, a 15 minute run and an hour Zoom meeting I've done nothing else all day! I was planning to do something else this afternoon. Ho hum. 

It's all because of the map and displaying full screen to give it the real-estate. Add in 3 depths of router-outlets and ended up nowhere. Router outlets seems to mess with css... display elements laying out the page have to be at the same router level. 

Anyway... the end result is that the detail panel is now behind a service because the top level url (map/platforms/:id) had to go, the upstart of that is it actually now behaves more like you wanted the other day. 

Deployments and selected platforms are both now query stings and can co-exist quite happily. Although the code probably needs a tidy through. It at least gives a slight increase to url consistency.

Oh, and you now have a sticky footer. Marginal gains... :-/

Bonus: the platform detail modal now animates off the screen which it didn't before. Yay! Though upwards for some reason. Booo. 

Have a play, probably some issues I've not noticed.

**Comment by SiBell** [comment]
Argh nightmare! Well done for pushing through. Looks great. I've added the content to the footer now, so it now looks pretty consistent with the other parts of the website. Although for some reason teal-900 looks different, god knows why, but doubt anyone will notice.

Only issue I found was that when you close the _platform detail modal_ the _platform_ query parameter isn't being removed from the URL. I had a quick look to see if I can do this, but I was struggling to work out where the best place to do this would be. Any thoughts?

**Comment by SiBell** [comment]
Also is the deployment query parameter supposed to be cleared from the URL when the a platform marker is clicked?

To replicate:

1. Load the map
2. Click a deployment in the legend
3. Click a marker on the map

**Comment by Gramcito** [comment]
For the second comment, which browser are you using? In chrome canary that does not happen.

**Comment by SiBell** [comment]
Chrome 83.0.4103.97. How weird that something like that would vary between versions.

**Comment by Gramcito** [comment]
Same issue in safari as Chrome, which is a weird issue as the query string is populated in the code. Might be related to using location rather than router.

**Comment by Gramcito** [comment]
All fixed. Interestingly the animation render in Canary is way, way better compared to Chrome.
